### ISSUE TITLE
No icons displayed for button_submit_tag

### ISSUE THREAD

**Issue by vitobotta** [thetron/css3buttons_rails_helpers#8]
Hi, first of all thanks a lot for this gem. I like the buttons and the quick and easy integration with Rails.
The only thing is that if I use the button_submit_tag in forms, icons are not displayed like for the button_link_to. Also, the styling is wrong for the button_submit_tag while is correct for the button_link_to. 

For the second issue, I am using this CSS so that the submit tag looks like the other buttons:

form.formtastic input.button {
    height: 25px;
       padding: 0.2em 1em 0.2em 2.5em;
    font-family: sans-serif;
    font-size: 11px;
    margin-left: 5px;
}

As you can see I am using Formtastic so perhaps some attributes need fixing because they were changed by Formtastic's CSS. But I haven't yet managed to get submit_tag buttons displayed with the icon. So for example if in a form I have this:

approve_button_submit_tag "Update project"

The submit button is rendered correctly (thanks to the CSS above) and works correctly, but the "approve" icon is not displayed.
See this picture for example: ![example](https://img.skitch.com/20110501-mtxrt63qt6pf2yq1kku85r3sij.jpg)

Any idea on how to fix this? 

Thanks in advance
Vito

**Comment by thetron** [comment]
Hi Vito, thanks for reporting this.

That's correct - the icons cannot be displayed on the submit tags, this is to do with some limitation that is briefly referred to on the [css3 github buttons page](http://nicolasgallagher.com/lab/css3-github-buttons/). However, as of right now, I am adding a feature that will allow you to insert `<button>` tags instead of submit tags, which will allow the use of icons in forms. Which will be part of version 0.9.4.

In regards to your formtastic issue, that is quite frustrating - I'm not really sure what the best solution would be here. I'm open to suggestions though? For now however, I might include your snippit in the readme, in case anyone else runs into this issue.

**Comment by thetron** [comment]
I've just pushed out the latest version (0.9.4) which contains the support for the `<button>` tag.

**Comment by vitobotta** [comment]
Hi thetron, thanks a lot for your reply. Do you mean I can now use icons with submit buttons, or that I can use normal buttons (thus with icons) instead of submit tags?

Cheers

**Comment by thetron** [comment]
Sorry, I meant that if you're wanting to use icons in your forms, you should use the `<button>` tag, like so:

```
approve_button_tag "Update project"
```
